swagger: "2.0"
info:
  title: "{{title}}"
  version: "1.0"
basePath: /v1
paths:
  /art-step/{articulation}/{reverse}/{numsteps}:
    post:
      summary: Move an articulation by steps
      description: Moves the articulation that you specify the number of steps in the direction specified
      operationId: Thor_Control.post_artsteps
      produces:
        - text/plain;
      responses:
        200:
          description: Command Return
          schema:
            type: string
          examples:
            "text/plain": "Moving Art1 FORWARD by 100 steps"
      parameters:
        - name: reverse
          in: path
          description: Reverses the default direction. Expects 0 or 1
          required: true
          type: string
        - name: articulation
          in: path
          description: Articulation Number (1-6)
          required: true
          type: string
        - name: numsteps
          in: path
          description: Number of Steps (int)
          required: true
          type: integer
  /art-degrees/{articulation}/{reverse}/{degrees}:
    post:
      summary: Move an articulation by degrees
      description: Moves the articulation that you specify the number of degrees in the direction specified
      operationId: Thor_Control.post_artdegrees
      produces:
        - text/plain;
      responses:
        200:
          description: Command Return
          schema:
            type: string
          examples:
            "text/plain": "Moving Art1 FORWARD by 100 degrees"
      parameters:
        - name: reverse
          in: path
          description: Reverses the default direction
          required: true
          type: string
        - name: articulation
          in: path
          description: Articulation
          required: true
          type: string
        - name: degrees
          in: path
          description: Number of Degrees
          required: true
          type: integer
  /gripper/{command}:
    post:
      summary: Open or close the gripper
      description: Opens or closes the gripper
      operationId: Thor_Control.post_gripper
      produces:
        - text/plain;
      responses:
        200:
          description: Command Return
          schema:
            type: string
          examples:
            "text/plain": "Closing the gripper"
      parameters:
        - name: command
          in: path
          description: Open or close the gripper
          required: true
          type: string
