swagger: "2.0"
info:
  title: "{{title}}"
  version: "1.0"
basePath: /v1
paths:
  /manualcontrol/{articulation}/{reverse}/{numsteps}:
    post:
      summary: Move the arm manually
      description: Moves the articulation that you specify the number of steps in the direction specified
      operationId: Thor_Control.post_manualcontrol
      produces:
        - text/plain;
      responses:
        200:
          description: Command Return
          schema:
            type: string
          examples:
            "text/plain": "Moving Art1 FORWARD by 100 steps"
      parameters:
        - name: reverse
          in: path
          description: Reverses the default direction 
          required: true
          type: string
        - name: articulation
          in: path
          description: Articulation
          required: true
          type: string
        - name: numsteps
          in: path
          description: Number of Steps
          required: true
          type: integer
